# Generated by Django 6.0.2 on 2026-02-09 10:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('prenom', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('adresse', models.TextField(blank=True)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('code_postal', models.CharField(blank=True, max_length=10)),
                ('pays', models.CharField(default='France', max_length=100)),
                ('type_client', models.CharField(choices=[('particulier', 'Particulier'), ('professionnel', 'Professionnel'), ('collectivite', 'Collectivité'), ('distributeur', 'Distributeur'), ('ambassadrice', 'Ambassadrice')], default='particulier', max_length=20)),
                ('entreprise', models.CharField(blank=True, help_text="Nom de l'entreprise si professionnel", max_length=200)),
                ('shopify_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('date_premier_achat', models.DateField(blank=True, null=True)),
                ('nombre_achats', models.IntegerField(default=0)),
                ('montant_total_achats', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tags', models.CharField(blank=True, help_text='Tags séparés par des virgules', max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('prenom', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('entreprise', models.CharField(blank=True, max_length=200)),
                ('statut', models.CharField(choices=[('prospect', 'Prospect'), ('en_cours', 'En cours'), ('gagne', 'Gagné'), ('perdu', 'Perdu')], default='prospect', max_length=20)),
                ('source', models.CharField(choices=[('site_web', 'Site Web'), ('reseau_social', 'Réseau Social'), ('recommandation', 'Recommandation'), ('salon', 'Salon/Événement'), ('publicite', 'Publicité'), ('autre', 'Autre')], default='site_web', max_length=20)),
                ('montant_estime', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('probabilite', models.IntegerField(default=50, help_text='Probabilité de conversion (0-100%)')),
                ('date_conversion_prevue', models.DateField(blank=True, null=True)),
                ('date_conversion', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('converti_en_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospect_origine', to='crm.client')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prospect',
                'verbose_name_plural': 'Prospects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_interaction', models.CharField(choices=[('appel', 'Appel téléphonique'), ('email', 'Email'), ('reunion', 'Réunion'), ('note', 'Note'), ('autre', 'Autre')], max_length=20)),
                ('sujet', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_interaction', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='crm.client')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('prospect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='crm.prospect')),
            ],
            options={
                'verbose_name': 'Interaction',
                'verbose_name_plural': 'Interactions',
                'ordering': ['-date_interaction'],
            },
        ),
    ]
