# Generated by Django 6.0.2 on 2026-02-09 10:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campagne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('type_campagne', models.CharField(choices=[('newsletter', 'Newsletter'), ('promotion', 'Promotion'), ('relance', 'Relance'), ('bienvenue', 'Bienvenue'), ('autre', 'Autre')], default='newsletter', max_length=20)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('planifiee', 'Planifiée'), ('active', 'Active'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='brouillon', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('date_envoi', models.DateTimeField(blank=True, null=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('segment', models.CharField(blank=True, help_text='Type de clients ciblés', max_length=100)),
                ('sujet', models.CharField(max_length=200)),
                ('contenu_html', models.TextField()),
                ('contenu_texte', models.TextField(blank=True)),
                ('emails_envoyes', models.IntegerField(default=0)),
                ('emails_ouverts', models.IntegerField(default=0)),
                ('clics', models.IntegerField(default=0)),
                ('conversions', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Campagne',
                'verbose_name_plural': 'Campagnes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SequenceEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('type_sequence', models.CharField(choices=[('bienvenue', 'Bienvenue'), ('panier_abandonne', 'Panier abandonné'), ('nurturing', 'Nurturing'), ('reactivation', 'Réactivation')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Séquence email',
                'verbose_name_plural': 'Séquences email',
            },
        ),
        migrations.CreateModel(
            name='EmailEnvoye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_email', models.CharField(choices=[('transactionnel', 'Transactionnel'), ('marketing', 'Marketing'), ('notification', 'Notification')], default='marketing', max_length=20)),
                ('statut', models.CharField(choices=[('envoye', 'Envoyé'), ('ouvert', 'Ouvert'), ('clique', 'Cliqué'), ('erreur', 'Erreur')], default='envoye', max_length=20)),
                ('sujet', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('date_envoi', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_ouverture', models.DateTimeField(blank=True, null=True)),
                ('date_clic', models.DateTimeField(blank=True, null=True)),
                ('erreur', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campagne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='marketing.campagne')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails_recus', to='crm.client')),
            ],
            options={
                'verbose_name': 'Email envoyé',
                'verbose_name_plural': 'Emails envoyés',
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='EmailSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.IntegerField(default=1)),
                ('delai_jours', models.IntegerField(default=0, help_text='Nombre de jours après le déclencheur')),
                ('sujet', models.CharField(max_length=200)),
                ('contenu_html', models.TextField()),
                ('contenu_texte', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='marketing.sequenceemail')),
            ],
            options={
                'verbose_name': 'Email de séquence',
                'verbose_name_plural': 'Emails de séquence',
                'ordering': ['sequence', 'ordre'],
            },
        ),
    ]
